print('Hello, World!')
print('I wanna sleep')
print('Salve')
print('É Nóiz')
print('Vai Corinthians!!!')
print('Tamo')
print('na')
print('Libertadores!!!')
print('Apenas um')
print('cara Tranquilo')